GOOGLE_API_KEY = "AIzaSyAv_zEKjnkyVOCk1hP7wgtSdLeLn5lxMjA"
BEATOVEN_API_KEY = "Af3AXn9T5X6DaY33Hwoy5Q"
PEXELS_API_KEY = "sp1tmMgrZwiiK6TOl6Vx7exmff1fo060zRxrFHbmA4bx0gIrsasiDHzS"
PIXABAY_API_KEY = "45869112-d39f3d6d9c1b002a660e1f929"

[gcp_service_account]
type = "service_account"
project_id = "gen-lang-client-0527116873"
private_key_id = "ddc2a26e07a73c7446bc14ce2bd2d33b7be1f52c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC0+R3wS8UXgI0I
gMcXYQ1B1D/PNpV5StHfmo9lqOeZ6Gc9yH8jYJsyZMsa48h9frH/t2/fqfP313RJ
SDKI6irfbScqm/rSbEIdhV9FnFz8yFNl97X2kEUZsX4qTBkgO7CA+E/J4C0ka0AJ
B3AF7HqKtmTUXRHxO7kjV52OhuCZ14f359d6tVmG1V7IblyRJeEhubjrgGds1AZ4
JUT72bWD9ZCvytrINS6IuQXJp0J81yr1GRpx1A+EwJykmDJXzwb4zqNh2hV2tA/j
ZbhyWMbwN1dsTFMWoMZJKKtoxF8lJrYy4rv5Pp2WBHAK+NOMTYOMbbl8XCqqfLLc
fR/+HusdAgMBAAECggEANbivtPnhF3FvLEOCFkQWmeCGUp4q7/cQZxasE6r4mVz+
bL48U4WlfGekTSaqCOrXrwfGm3gJdpyMJgbbDX6p3Go8Eq973QQK+lVxqynYBqf2
7dGDQB6ijJZ+U9MEMGfXpOlRUiWMcP+vYh7Fl9STqeKr+shn/5rRghbLrBgIy1HJ
0riyiHqo6hQeIVfVrjnvM3d+A5rINobLWrdh0Q8mvd633W7Kq5dnfZrc0UWyjuW9
CRJgUj0Rl9nNm+5zQEcjqd57u7YzMBXcyzBYDQn0nPpuP0G+AkFUaDvb6YZt4N4v
1P6EkBJ7WmiFO0MzD1Hbt2XyMaCOwUZNc7pWdvyzVwKBgQDucOalmFw0mUv0du4b
MBVAJyNCbHQtjWh9iAt7DKJuNNqhJMwC8vC94sKbPG53jE2WBssvLQ3EUBMEwXUz
NI/bgj4TvTQkTDGvme+GUn7xQMgZNSf1ufb75d9N1emUs4pWsM0v09bt7QcR03o8
+kLS7EDHwH43rcRPXKxJIIxPqwKBgQDCTNQwI2dAgyxCuUXKQDFG66tpgCYylCGa
Z/0K8LJc73XQi48rLTNl7iQf7Pqh3OF1NQ3tvAP3GFd9D0pnuMDOOBCEWam9Xmum
+4a4YTYM40YDYSOLm+aHq9xtdT4b4w88DJBdiTwIUCmDq32945hdZ8Y7L5imOhYJ
ov4H81eIVwKBgQDSAgqDa1A625H0fRN2SsFMwavigxdIT7XqanqCJDykCFVPfNNa
/ZJgDGsOwwkgrihfrRgkMvBfKY+2rpWFRhQ2Z945EHnuRlW0rkYy7lH0NvSGjzTk
zqfkcTBeo7uZRxDfDdWK/G/fGtcRMkwFjP5yO7dKuBXzAE9Y/uyXc91hBQKBgAWD
sLH9Dz0he+wY3gYzdDKTFbZU0MC2u41qTiA1XJqOoUVd8J5FFiRaceQGEcbuQefV
raOFpocoxbLi8DWpZK91n+JhuROKzntawCQTfjk3ahFGfH/F2PEYy5S/sxePhisq
IB7HelCyFbuK7nKpNvXPsCyV2Ts+gsmbOqJ3IZDZAoGBAMQDjP3EKyiXS5ZD1PAp
WU7sNW/nVD+cc3OUwb0c2Nt4U2aLJpP/wM0sTYX+k5+EQ9MZJIiT895z1kJ9KrMt
ih4C51YSfonlmX7mbwDfMM392SMCOQuDV18EY6wVcVRgqZQiaFRtZQLbq7fenxXP
uQkkAs6a0YeXbawjfyhdudr3
-----END PRIVATE KEY-----
"""
client_email = "video-generator-tts@gen-lang-client-0527116873.iam.gserviceaccount.com"
client_id = "106345694313722978967"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
